### ISSUE TITLE
Initial Questions

### ISSUE THREAD

**Issue by johnmclives** [Nicuz/Bulmascores#3]
Hi there, I'm really loving this starter theme, thank you very much!

However, I have some questions about using it, and hopefully you'll be able to help a newbee out. 

1. I'm currently learning Sass for the first time, and badly want to use Bulma, so your theme was a no brainer.

2. The problem comes when I try to make changes to the Sass files. This might be an obvious question for you, but not for me! Do you make changes to the Sass files that already exist? I read that a preprocessor is needed. In that case, can I use Prepos, for example? I'm using a Windows 10 machine. 

3. If Prepos is the right one, then as I understand it, I just need to install Bulmascores on my themes folder, and then drag the entire Bulmascores theme to Prepos, am I right? Then, making changes to the Sass files should then be reflected, am I right?

4. Besides Bulma installed, and the slider, am I right to assume that this theme is entirely from scratch, as if it was just installed from Underscores site?

5. If there are changes to Bulma in the future, how might we update our files then?

It's a lot of questions, I know, but thank you so much!

Any help will be appreciated 😊

**Comment by Nicuz** [comment]
Hi @johnmclives, I'm glad you liked Bulmascores! Let's try to answer in order:

1. A little tip that may work for you too: if you noticed in the sass folder there's a "components" one. I generally organize every part of the template accordingly to the Bulma documentation. For instance, navbar is a component, box is an element (so I would create an element folder) and so on. It makes easier to me know where every part of the template is. And yes, footer is in the wrong folder and I should fix 😅

2. Yep, I edit the existing files. I personally use [gulp](https://gulpjs.com/) as task runner. There's a [gulpfile](https://github.com/Nicuz/Bulmascores/blob/master/gulpfile.js) in the root of the theme, it provides all you need to automatically compile the sass files into a minified css. There are also other features like auto-prefixing and live preview of changes without the need of refreshing your browser tab, just open the URL it provides after launching it.

3. Install Bulmascores, install npm and gulp, open a command prompt window, cd into Bulmascores folder, run _npm start_ and you're good to go. Sass files will be automatically compiled everytime you change something in your source code and save! 😄

4. You're right, Bulmascores is based on Underscores. I wanted a clean base to start with, I only added Bulma support and other little things that could speed up my workflow when developing themes.

5. Go into functions.php and replace the Bulma's URL with the latest one, same for FontAwesome and Flickity. 

If you need further information don't hesitate to comment 😉
